apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-api
  labels:
    app: s3-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s3-api
  template:
    metadata:
      labels:
        app: s3-api
    spec:
      containers:
      - name: s3-api
        image: s3-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-key
        - name: AWS_REGION
          value: "ap-northeast-1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 